# Generated by Django 2.0.7 on 2018-07-27 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('odds', models.DecimalField(
                    choices=[(-5.0, -5.0), (-4.75, -4.75), (-4.5, -4.5), (-4.25, -4.25), (-4.0, -4.0), (-3.75, -3.75), (-3.5, -3.5), (-3.25, -3.25),
                             (-3.0, -3.0), (-2.75, -2.75), (-2.5, -2.5), (-2.25, -2.25), (-2.0, -2.0), (-1.75, -1.75), (-1.5, -1.5), (-1.25, -1.25),
                             (-1.0, -1.0), (-0.75, -0.75), (-0.5, -0.5), (-0.25, -0.25), (0.0, 0.0), (0.25, 0.25), (0.5, 0.5), (0.75, 0.75),
                             (1.0, 1.0), (1.25, 1.25), (1.5, 1.5), (1.75, 1.75), (2.0, 2.0), (2.25, 2.25), (2.5, 2.5), (2.75, 2.75), (3.0, 3.0),
                             (3.25, 3.25), (3.5, 3.5), (3.75, 3.75), (4.0, 4.0), (4.25, 4.25), (4.5, 4.5), (4.75, 4.75)], decimal_places=2,
                    default=0, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('home_goals', models.PositiveIntegerField()),
                ('guest_goals', models.PositiveIntegerField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tournaments.Match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('founded_at', models.PositiveIntegerField(default=2018)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='team_symbols')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.ManyToManyField(related_name='teams', to='tournaments.Tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_matches', to='tournaments.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournaments.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.Tournament'),
        ),
    ]
